module.exports = [
  {
    team: "fenerbahce@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1669152785/logo/Fenerbah_C3_A7e_SK_pjkz7b.png",
    name: "Fenerbahce",
    displayName: "Fenerbahçe",
  },
  {
    name: "Galatasaray",
    team: "galatasaray@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1669152685/logo/1024px-Galatasaray_Star_Logo_xegni9.png",
    displayName: "Galatasaray",
  },
  {
    name: "Adanademirspor",
    team: "adanademirspor@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262421/logo/Adana_Demirspor_logo_oxhrqz.png",
    displayName: "Adana Demirspor",
  },
  {
    name: "Konyaspor",
    team: "konyaspor@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262427/logo/Konyaspor_logo.svg_dbwgot.png",
    displayName: "Konyaspor",
  },
  {
    name: "Basaksehir",
    team: "basaksehir@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1669152717/logo/1024px-_C4_B0stanbul_Ba_C5_9Fak_C5_9Fehir_logo.svg_yenxew.png",
    displayName: "İstanbul Başakşehir",
  },
  {
    name: "Kayseri",
    team: "kayseri@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262428/logo/Kayserispor_logo.svg_hluevp.png",
    displayName: "Kayserispor",
  },
  {
    name: "Trabzonspor",
    team: "trabzonspor@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1669152733/logo/800px-Trabzonspor_Amblem.svg_pmlhvn.png",
    displayName: "Trabzonspor",
  },
  {
    name: "Besiktas",
    team: "besiktas@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262422/logo/BesiktasJK-Logo.svg_oit9zl.png",
    displayName: "Beşiktaş",
  },
  {
    name: "Alanyaspor",
    team: "alanyaspor@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262426/logo/Alanyaspor_logo.svg_hf5vmb.png",
    displayName: "Alanyaspor",
  },
  {
    name: "Gaziantep",
    team: "gaziantep@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1669152744/logo/1920px-Gaziantepspor_logo.svg_notcr1.png",
    displayName: "Gaziantep",
  },
  {
    name: "Antalyaspor",
    team: "antalyaspor@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262424/logo/Antalyaspor_logo.svg_dv20jg.png",
    displayName: "Antalyaspor",
  },
  {
    name: "Giresun",
    team: "giresun@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262422/logo/Giresunspor_bw32jf.png",
    displayName: "Giresunspor",
  },
  {
    name: "Kasımpasa",
    team: "kasımpasa@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262423/logo/Kasimpasa_logo.svg_lbmw9q.png",
    displayName: "Kasımpaşa",
  },
  {
    name: "Hatay",
    team: "hatay@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262423/logo/Hatayspor_nhve1s.gif",
    displayName: "Hatayspor",
  },
  {
    name: "Fatihkaragumruk",
    team: "fatihkaragumruk@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262422/logo/Fatih_Karagu%CC%88mru%CC%88k_S.K._cp1b5c.png",
    displayName: "Fatih Karagümrük",
  },
  {
    name: "Ankaragucu",
    team: "ankaragucu@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262426/logo/Ankaragucu_logo.svg_azbqll.png",
    displayName: "Ankaragücü",
  },
  {
    name: "Sivasspor",
    team: "sivasspor@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262427/logo/Sivasspor_logo.svg_kvvwmj.png",
    displayName: "Sivasspor",
  },
  {
    name: "Istanbulspor",
    team: "istanbulspor@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262424/logo/Istanbulspor.svg_dfkftu.png",
    displayName: "İstanbulspor",
  },
  {
    name: "Umraniye",
    team: "umraniye@gmail.com",
    url: "https://res.cloudinary.com/dbb2x1zfs/image/upload/v1672262427/logo/U%CC%88mraniyespor_logo_kzqf8s.png",
    displayName: "Ümraniye",
  },
];
