module.exports = [
  {
    name: "Rafi",
    lastname: "Banana",
    email: "rafi@gmail.com",
    password: "123",
    type: "fan",
  },
  {
    name: "Mustafa",
    lastname: "Gedikoğlu",
    email: "mustafa@gmail.com",
    password: "123",
    type: "fan",
  },
  {
    name: "Elif",
    lastname: "Öztürk",
    email: "elif@gmail.com",
    password: "123",
    type: "fan",
  },
  {
    name: "Egemen",
    lastname: "Esen",
    email: "egemenesen@sabanciuniv.edu",
    password: "123",
    type: "fan",
  },
  {
    name: "Fenerbahce",
    lastname: "SK",
    email: "fenerbahce@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Galatasaray",
    lastname: "SK",
    email: "galatasaray@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Basaksehir",
    lastname: "SK",
    email: "basaksehir@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Trabzonspor",
    lastname: "SK",
    email: "trabzonspor@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Besiktas",
    lastname: "JK",
    email: "besiktas@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Gaziantep",
    lastname: "SK",
    email: "gaziantep@gmail.com",
    password: "123",
    type: "team",
  },
];
