module.exports = [
  {
    name: "Rafi",
    lastname: "Banana",
    email: "rafi@gmail.com",
    password: "123",
    type: "fan",
  },
  {
    name: "Mustafa",
    lastname: "Gedikoğlu",
    email: "mustafa@gmail.com",
    password: "123",
    type: "fan",
  },
  {
    name: "Elif",
    lastname: "Öztürk",
    email: "elif@gmail.com",
    password: "123",
    type: "fan",
  },
  {
    name: "Egemen",
    lastname: "Esen",
    email: "egemenesen@sabanciuniv.edu",
    password: "123",
    type: "fan",
  },
  {
    name: "Fenerbahce",
    lastname: "SK",
    email: "fenerbahce@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Galatasaray",
    lastname: "SK",
    email: "galatasaray@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Basaksehir",
    lastname: "SK",
    email: "basaksehir@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Trabzonspor",
    lastname: "SK",
    email: "trabzonspor@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Besiktas",
    lastname: "JK",
    email: "besiktas@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Gaziantep",
    lastname: "SK",
    email: "gaziantep@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Adanademirspor",
    lastname: "SK",
    email: "adanademirspor@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Konyaspor",
    lastname: "SK",
    email: "konyaspor@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Kayseri",
    lastname: "SK",
    email: "kayseri@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Alanyaspor",
    lastname: "SK",
    email: "alanyaspor@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Adanademirspor",
    lastname: "SK",
    email: "adanademirspor@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Antalyaspor",
    lastname: "SK",
    email: "antalyaspor@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Giresun",
    lastname: "SK",
    email: "giresun@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Kasımpasa",
    lastname: "SK",
    email: "kasımpasa@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Hatay",
    lastname: "SK",
    email: "hatay@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Fatihkaragumruk",
    lastname: "SK",
    email: "fatihkaragumruk@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Ankaragucu",
    lastname: "SK",
    email: "ankaragucu@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Sivasspor",
    lastname: "SK",
    email: "sivasspor@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Istanbulspor",
    lastname: "SK",
    email: "istanbulspor@gmail.com",
    password: "123",
    type: "team",
  },
  {
    name: "Umraniye",
    lastname: "SK",
    email: "umraniye@gmail.com",
    password: "123",
    type: "team",
  },
];
